# Generated by Django 5.2.8 on 2026-03-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_master', '0002_alter_project_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='student_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
